[maintenance]: drop db_process, unused and broken
xapi-db-process is unused, and doesn't work:
```
/opt/xensource/bin/xapi-db-process -filename state.db
Fatal error: exception Db_exn.DBCache_NotFound("missing table", "Certificate", "")
```

Signed-off-by: Edwin Török <edwin.torok@cloud.com>